---
- name: Install deps
  ansible.builtin.apt:
    lock_timeout: 240
    update_cache: true
    pkg:
      - apt-transport-https
      - ca-certificates

- name: Check ansible_vpp_install_type
  ansible.builtin.fail:
    msg: "ansible_vpp_install_type is '{{ ansible_vpp_install_type }}' when it should be 'source' or 'binary'"
  when: ansible_vpp_install_type is defined and ansible_vpp_install_type != "source" and ansible_vpp_install_type != "binary"

- name: Binary install
  ansible.builtin.include_tasks: binary_install.yml
  when: not (ansible_vpp_install_type is defined) or ansible_vpp_install_type != "source"

- name: Source install
  ansible.builtin.include_tasks: source_install.yml
  when: ansible_vpp_install_type is defined and ansible_vpp_install_type == "source"

- name: Create log directory so service doesn't crash
  ansible.builtin.file:
    path: /var/log/vpp/
    state: directory
    mode: '0600'
    owner: root
    group: vpp

- name: Setup vppcfg
  ansible.builtin.include_tasks: vppcfg.yml
  when: ansible_vpp_setup_vppcfg is defined and ansible_vpp_setup_vppcfg

- name: VPP Config
  ansible.builtin.template:
    src: vpp.conf.j2
    dest: /etc/vpp.conf
    owner: root
    group: root
    mode: "640"
  when: ansible_vpp_deploy_config is defined and ansible_vpp_deploy_config

- name: Set sysctls
  ansible.builtin.copy:
    content: "{{ ansible_vpp_sysctls }}"
    dest: /etc/sysctl.d/80-vpp.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_vpp_sysctls is defined and ansible_vpp_sysctls != ""

- name: Apply sysctls
  ansible.builtin.command:
    cmd: sysctl --all
  when: ansible_vpp_sysctls is defined and ansible_vpp_sysctls != ""

- name: Add user {{ item }} to vpp group
  ansible.builtin.user:
    name: "{{ item }}"
    group: vpp
    append: true
  loop: "{{ ansible_vpp_add_user_to_vpp.split(',') }}"
  when: ansible_vpp_add_user_to_vpp is defined and ansible_vpp_add_user_to_vpp != ""
