- name: Install build deps
  ansible.builtin.apt:
    lock_timeout: 240
    update_cache: true
    pkg:
      - git
      - make

- name: Git checkout
  ansible.builtin.git:
    repo: "https://gerrit.fd.io/r/vpp"
    dest: /root/vpp_src
    version: master

- name: Install build deps via makefile
  ansible.builtin.command:
    cmd: make UNATTENDED=y install-dep
    chdir: /root/vpp_src

- name: Get external dependencies
  ansible.builtin.command:
    cmd: make install-ext-deps
    chdir: /root/vpp_src

- name: Run release build
  ansible.builtin.command:
    cmd: make build-release
    chdir: /root/vpp_src

- name: Run package build
  ansible.builtin.command:
    cmd: make pkg-deb
    chdir: /root/vpp_src

- name: Install package
  ansible.builtin.command:
    cmd: dpkg -i build-root/*.deb
    chdir: /root/vpp_src
